### ISSUE TITLE
找不到privateKeys.keystore 

### ISSUE THREAD

**Issue by wedtlcy** [zifangsky/LicenseDemo#1]
您好，一直报错，java.io.FileNotFoundException: E:\github\license_demos\LicenseDemo\ServerDemo\src\main\resources\privateKeys.keystore (系统找不到指定的文件。)指定路径和项目路径都试了，求大佬支持！

**Comment by zifangsky** [comment]
> 您好，一直报错，java.io.FileNotFoundException: E:\github\license_demos\LicenseDemo\ServerDemo\src\main\resources\privateKeys.keystore (系统找不到指定的文件。)指定路径和项目路径都试了，求大佬支持！

首先先生成`privateKeys.keystore`这个文件，然后指定文件所在的绝对路径就可以了（PS：Windows环境的路径最好用`/`或者`\\`吧）。

**Comment by wedtlcy** [comment]
> > 您好，一直报错，java.io.FileNotFoundException: E:\github\license_demos\LicenseDemo\ServerDemo\src\main\resources\privateKeys.keystore (系统找不到指定的文件。)指定路径和项目路径都试了，求大佬支持！
> 
> 首先先生成`privateKeys.keystore`这个文件，然后指定文件所在的绝对路径就可以了（PS：Windows环境的路径最好用`/`或者`\\`吧）。

可以了，谢谢大佬。
