### ISSUE TITLE
如何获取license里面的其他参数，比如放在里面的授权信息

### ISSUE THREAD

**Issue by Inaisen** [zifangsky/LicenseDemo#2]

**Comment by zifangsky** [comment]
自行看 [github.com/zifangsky/LicenseDemo/blob/master/ClientDemo/src/main/java/cn/zifangsky/license/CustomLicenseManager.java](github.com/zifangsky/LicenseDemo/blob/master/ClientDemo/src/main/java/cn/zifangsky/license/CustomLicenseManager.java)这个类里面的`validateCreate`和`validate`方法。
